use football_uz;

-- CREATE STATEMENTS

CREATE TABLE TEAMS (
	TEAM_ID INT PRIMARY KEY,
    TEAM_NAME VARCHAR(30),
    COUNTRY VARCHAR(30),   
    );
   
CREATE TABLE PLAYERS (
	PLAYER_ID INT PRIMARY KEY,
	TEAM_ID INT,
	PLAYER_NAME VARCHAR(20),
    POSITION_PLAYER INT,
    CLUB VARCHAR(30),
    NATIONALITY VARCHAR(30),
    AGE INT
    FOREIGN KEY(TEAM_ID) references TEAMS(TEAM_ID)
    );
   
CREATE TABLE POSITION_STATS(
	POSITION_ID INT PRIMARY KEY,
    POSITION_NAME VARCHAR(20)
    );
   
CREATE TABLE MATCHES(
	MATCH_ID INT PRIMARY KEY,
    MATCH_DATE_TIME DATETIME,
    HOME_TEAM VARCHAR(30),
    AWAY_TEAM VARCHAR(30),
    MATCH_GOALS int,
    STADIUM_LOCATION VARCHAR(30)
    );
    
CREATE TABLE COACH (
	COACH_ID VARCHAR(30),
	TEAM_ID INT,
    COACH_NAME VARCHAR(30),
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(TEAM_ID)
    );
   
 
CREATE TABLE STADIUM (
	STADIUM_ID INT PRIMARY KEY,
    STADIUM_NAME VARCHAR(50),
    CITY VARCHAR(20),
    MATCH_ID INT,
    FOREIGN KEY(MATCH_ID ) REFERENCES MATCHES(MATCH_ID)
    );
  desc COACH;
  

 
CREATE TABLE GOAL(
	GOAL_ID INT PRIMARY KEY,
    MATCH_ID INT,
    PLAYER_ID INT,
    GOAL_TIME TIME,
    FOREIGN KEY (MATCH_ID ) references MATCHES(MATCH_ID ),
    FOREIGN KEY (PLAYER_ID) references PLAYERS(PLAYER_ID)
    );

CREATE TABLE CARDS (
	CARD_ID INT PRIMARY KEY,
	match_id int,
	player_id int,
	team_id int,
	FOREIGN KEY (MATCH_ID ) references MATCHES(MATCH_ID ),
    FOREIGN KEY (PLAYER_ID) references PLAYERS(PLAYER_ID),
    FOREIGN KEY (team_id) references teams(team_id),
    CARD_TYPE VARCHAR(20),
    card_time datetime
    );
   
CREATE TABLE REFREE (
	REFREE_ID INT primary KEY,
    REFREE_NAME VARCHAR(30),
    COUNTRY VARCHAR(20),
    MATCH_ID INT,
    CARD_ID INT,
    foreign key (MATCH_ID) references MATCHES(MATCH_ID),
    foreign key (CARD_ID) references CARDS(CARD_ID)
    );






